### ISSUE TITLE
Make work with mods

### ISSUE THREAD

**Issue by Eugenii10** [justarandomgeek/factorio-wirestripper#1]
Hello! Thanks for a great mod from the category "should be there from the box" :) It's a pitty that it doesn't work with mods (or at least with "bobpower" accumulators), I had to remove green/red wires by the hand.

**Comment by justarandomgeek** [comment]
It currently only works with power poles (including modded ones), not any other entity types. Still undecided on whether or not it should strip circuit wires from other types...
